-- Phase 16: airworthiness M2 — work orders as the maintenance record,
-- components with their own hours, defects reported by pilots.
--
-- Design (docs/PHASE_16_PLAN.md):
--  * a component is a club-level thing (part number + serial); an
--    installation binds it to an aircraft for a period; its hours follow
--    the aircraft while installed and freeze at removal;
--  * limits on a component are ordinary tasks with component_id;
--  * work orders gain a cancelled state; items carry component swaps,
--    parts used and the defect they rectify;
--  * defects go open -> rectified | deferred | closed; unassessed ones put
--    the aircraft in attention, ones affecting airworthiness ground it.

-- ---------- components ----------
create table mx_components (
	id uuid primary key default gen_random_uuid(),
	part_number text not null,
	serial_number text not null,
	description text not null,
	ata_chapter text,
	parent_component_id uuid references mx_components (id),
	manufacture_date date,
	-- Form 1 / 8130-3 number; the document itself arrives in M3
	traceability_ref text,
	notes text,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint mx_components_identity unique (part_number, serial_number),
	constraint mx_components_serial_present check (length(trim(serial_number)) > 0)
);

create table mx_component_installations (
	id uuid primary key default gen_random_uuid(),
	component_id uuid not null references mx_components (id),
	aircraft_id uuid not null references aircraft (id) on delete cascade,
	position text,
	installed_on date not null,
	-- aircraft readings at fitting
	installed_at_hours numeric(8, 1) not null,
	installed_at_landings integer not null,
	-- component readings at fitting
	tsn_at_install numeric(8, 1) not null default 0,
	tso_at_install numeric(8, 1) not null default 0,
	csn_at_install integer not null default 0,
	removed_on date,
	removed_at_hours numeric(8, 1),
	removed_at_landings integer,
	removed_reason text,
	install_work_order_id uuid references mx_work_orders (id),
	remove_work_order_id uuid references mx_work_orders (id),
	created_at timestamptz not null default now(),
	constraint mx_installations_removal_complete check (
		(removed_on is null) = (removed_at_hours is null) and (removed_on is null) = (removed_at_landings is null)),
	constraint mx_installations_order check (removed_on is null or removed_on >= installed_on)
);
-- a component is installed in one place at a time
create unique index mx_installations_one_open on mx_component_installations (component_id) where removed_on is null;
create index mx_installations_aircraft_idx on mx_component_installations (aircraft_id, installed_on desc);
create index mx_installations_component_idx on mx_component_installations (component_id, installed_on desc);

-- a task may belong to a component: its hours and landings are the component's
alter table mx_tasks add column component_id uuid references mx_components (id);
create index mx_tasks_component_idx on mx_tasks (component_id) where component_id is not null;

-- ---------- work orders ----------
-- Postgres 16 allows adding an enum value inside a transaction as long as
-- the value is not used in the same transaction; nothing below uses it.
alter type mx_work_order_status add value 'cancelled';
alter table mx_work_orders
	add column cancelled_at date,
	add column cancelled_reason text,
	add column cancelled_by uuid references users (id),
	-- approval / licence reference of the organisation or person
	add column performed_by_ref text;
alter table mx_work_order_items
	add column removed_component_id uuid references mx_components (id),
	add column installed_component_id uuid references mx_components (id),
	add column installed_tsn numeric(8, 1),
	add column installed_tso numeric(8, 1),
	add column installed_csn integer,
	add column position_label text,
	add column defect_id uuid,
	-- [{part_number, serial_number, quantity, traceability}]
	add column parts_used jsonb not null default '[]';

-- ---------- defects ----------
create type mx_defect_status as enum ('open', 'deferred', 'rectified', 'closed');

create table mx_defects (
	id uuid primary key default gen_random_uuid(),
	number integer generated by default as identity unique,
	aircraft_id uuid not null references aircraft (id) on delete cascade,
	reported_by uuid not null references users (id),
	reported_at timestamptz not null default now(),
	flight_log_id uuid references flight_log_entries (id) on delete set null,
	title text not null,
	description text,
	status mx_defect_status not null default 'open',
	-- null until the technical manager has assessed it
	affects_airworthiness boolean,
	assessed_by uuid references users (id),
	assessed_at timestamptz,
	assessment text,
	-- deferral (ML.A.403): who assessed it as not hazardous, on what basis, until when
	deferred_by text,
	deferred_on date,
	deferral_basis text,
	deferral_limit_date date,
	deferral_limit_hours numeric(8, 1),
	rectified_work_order_id uuid references mx_work_orders (id),
	rectified_on date,
	closed_at timestamptz,
	closed_by uuid references users (id),
	closed_reason text,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint mx_defects_deferral_complete check (
		status <> 'deferred' or (deferred_by is not null and deferral_basis is not null
		                          and (deferral_limit_date is not null or deferral_limit_hours is not null))),
	constraint mx_defects_rectified_complete check (status <> 'rectified' or rectified_work_order_id is not null),
	constraint mx_defects_closed_complete check (status <> 'closed' or closed_reason is not null)
);
create index mx_defects_aircraft_idx on mx_defects (aircraft_id, status);
alter table mx_work_order_items add constraint mx_work_order_items_defect_fk foreign key (defect_id) references mx_defects (id);

-- Photos in their own table so lists never drag bytes along (like receipt_images).
create table mx_defect_images (
	id uuid primary key default gen_random_uuid(),
	defect_id uuid not null references mx_defects (id) on delete cascade,
	content_type text not null,
	bytes bytea not null,
	width integer not null,
	height integer not null,
	created_at timestamptz not null default now()
);
create index mx_defect_images_defect_idx on mx_defect_images (defect_id);
